import Link from "next/link";
import Image from "next/image";
import type { Product } from "@/lib/content";
import { breadcrumbJsonLd, productServiceJsonLd } from "@/lib/seo";

export function Arrow() { return <span aria-hidden="true">↗</span>; }
export function JsonLd({ data }: { data: object }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />; }
export function PageHero({ eyebrow, title, description, dark = false }: { eyebrow: string; title: React.ReactNode; description: string; dark?: boolean }) { return <section className={dark ? "page-hero page-hero--dark" : "page-hero"}><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-hero__copy">{description}</p></div></section>; }
export function ContactCTA({ children }: { children?: React.ReactNode } = {}) { return <section className="cta"><div className="container cta-inner"><div><p className="eyebrow">LET&apos;S BUILD TOGETHER</p><h2>새로운 비즈니스의 시작,<br />Jervis Labs와 함께 하세요.</h2></div><Link className="button button--light" href="/contact">상담 문의 <Arrow /></Link></div>{children && <div className="container cta-sponsor">{children}</div>}</section>; }

export function ProductLanding({ product }: { product: Product }) {
  return <>
    <JsonLd data={productServiceJsonLd(product)} />
    <JsonLd data={breadcrumbJsonLd([{ name: "홈", path: "/" }, { name: "솔루션", path: "/product" }, { name: product.name, path: `/product/${product.slug}` }])} />
    <section className={`product-hero ${product.accent}`}><div className="container product-hero__grid"><div><p className="eyebrow">{product.status}</p><h1>{product.name}</h1><p className="product-category">{product.category}</p><h2>{product.tagline}</h2><p className="product-description">{product.description}</p><div className="hero-actions">{product.demo ? <a className="button" href={product.demo} target="_blank" rel="noreferrer">{product.demoLabel ?? "데모 서비스"} <Arrow /></a> : <span className="button button--disabled">COMING SOON</span>}<Link className="button button--secondary" href="/contact">도입 문의</Link></div></div>{product.posterImage ? <div className="product-poster"><Image src={product.posterImage} width={891} height={1270} alt={`${product.name} 포스터`} /></div> : <div className="product-console"><div className="console-top"><span>{product.name.toUpperCase()}</span><i /></div><div className="console-mark">{product.markImage ? <Image src={product.markImage} width={120} height={120} alt={`${product.name} 아이콘`} /> : product.name.slice(0, 2).toUpperCase()}</div><p>{product.category}</p><div className="console-status"><span>STATUS</span><strong>{product.demo ? "SERVICE READY" : "IN DEVELOPMENT"}</strong></div></div>}</div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">CORE FEATURES</p><h2>서비스의 핵심 기능</h2></div><div className="feature-grid">{product.features.map(([title, copy], index) => <article className="feature-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section section--subtle"><div className="container"><div className="section-heading"><p className="eyebrow">HOW IT WORKS</p><h2>간결하고 검증 가능한 흐름</h2></div><div className="flow-grid">{product.flow.map(([title, copy], index) => <article key={title}><span>STEP 0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="audience"><p className="eyebrow">BUILT FOR</p><div>{product.audiences.map((item) => <span key={item}>{item}</span>)}</div></div></div></section><ContactCTA /></>;
}
